myapp/urls.py
from django.urls import path
from myapp import views
app_name="myapp"

urlpatterns = [
    path('trail/',views.trial,name="Trial"),
    path('profile/',views.profile,name="profile"),
    path('get_demo/',views.get_demo,name="get_demo"),
    path('post_demo/',views.post_demo,name="post_demo"),
    path('register/',views.register,name="register"),
    path('multi/',views.multi,name="multiselect"),
    path('img/',views.img_upld,name="img"),
    path('img_diplay/',views.img_display,name="img_disp"),
    path('builtin/',views.builtinforms,name="builtin"),
]

p21/urls.py
from django.contrib import admin
from django.urls import path,include
import myapp
from myapp import views

#import settings and static to connect media url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('base/',views.base,name="base"),
    path('',views.home,name="home"),
    path('myapp/',include("myapp.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) #list concat

myapp/models.py
from django.db import models

# Create your models here.

myapp/forms.py
from django import forms

choices_day=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31')]
choices_month=[('1','Jan'),('2','Feb'),('3',"Mar"),("4","April")]
choices_year=[('1947', '1947'), ('1948', '1948'), ('1949', '1949'), ('1950', '1950'), ('1951', '1951'), ('1952', '1952'), ('1953', '1953'), ('1954', '1954'), ('1955', '1955'), ('1956', '1956'), ('1957', '1957'), ('1958', '1958'), ('1959', '1959'), ('1960', '1960'), ('1961', '1961'), ('1962', '1962'), ('1963', '1963'), ('1964', '1964'), ('1965', '1965'), ('1966', '1966'), ('1967', '1967'), ('1968', '1968'), ('1969', '1969'), ('1970', '1970'), ('1971', '1971'), ('1972', '1972'), ('1973', '1973'), ('1974', '1974'), ('1975', '1975'), ('1976', '1976'), ('1977', '1977'), ('1978', '1978'), ('1979', '1979'), ('1980', '1980'), ('1981', '1981'), ('1982', '1982'), ('1983', '1983'), ('1984', '1984'), ('1985', '1985'), ('1986', '1986'), ('1987', '1987'), ('1988', '1988'), ('1989', '1989'), ('1990', '1990'), ('1991', '1991'), ('1992', '1992'), ('1993', '1993'), ('1994', '1994'), ('1995', '1995'), ('1996', '1996'), ('1997', '1997'), ('1998', '1998'), ('1999', '1999'), ('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020')]

class SampleForm(forms.Form):
    first_name=forms.CharField(max_length=20,required=True,label="First Name",help_text="Note:Space and Spl charecters are not allowed")
    last_name=forms.CharField(max_length=20,required=False,label="Last Name",widget=forms.TextInput(attrs={'placeholder':"last name"}))
    email=forms.EmailField(max_length=100,required=True,label="Email")
    #phno=forms.IntegerField(max_value=9999999999,min_value=6000000000,required=True,label="Phone No",help_text="No courty codes")
    phno=forms.CharField(max_length=10,min_length=10,required=True,widget=forms.TextInput(attrs={'pattern':'[6-9]\d{9}'}))
    pwd=forms.CharField(max_length=20,required=True,widget=forms.PasswordInput)
    birth_day=forms.ChoiceField(choices=choices_day,required=True,label="Birth Day")
    birth_month=forms.ChoiceField(choices=choices_month,required=True,label="Birth Month")
    birth_year=forms.ChoiceField(choices=choices_year,required=True,label="Birth Year")
    gender=forms.ChoiceField(choices=[('Male','Male'),('Female','Female')],widget=forms.RadioSelect)
    image=forms.ImageField(max_length=200,allow_empty_file=False,required=True,label="Profile Pic")

myapp/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.core.mail import send_mail

# Create your views here.
def trial(request):
    return HttpResponse("<h1>Project is on air</h1>")

def base(request):
    return render(request,"base.html")

def home(request):
    return render(request,"myapp/home.html")

def profile(request):
    name="Ravi"
    return render(request,"myapp/profile.html",{'name':name})

def get_demo(request):
    name=request.GET.get('name')
    return render(request,"get_demo.html",{'name':name})


def post_demo(request):
    if request.method=="POST":
        name=request.POST.get('name')
        return HttpResponse("<h1>Thanks for submission Mr./Ms. {}</h1>".format(name))
    return render(request,"post_demo.html")

def register(request):
    if request.method=="POST":
        first_name=request.POST.get("first_name")
        last_name=request.POST.get("last_name")
        email=request.POST.get("email")
        password=request.POST.get("pwd")
        phno=request.POST.get("phno")
        date=request.POST.get("birthday_day")
        month=request.POST.get("birthday_month")
        year=request.POST.get("birthday_year")
        gender=request.POST.get("sex")
        if gender=="1":
            gender="FeMale"
        else:
            gender="Male"
        send_mail("Thanks For Registration","hello Mr./Ms.{} {}\n Thanks for Registering".format(first_name,last_name),
        "pr4413849@gmail.com",[email,],fail_silently=True)
        return redirect("home")
    return render(request,"myapp/registrations.html")


def multi(request):
    if request.method=="POST":
        foods=request.POST.getlist("food")
        languages=request.POST.getlist("language")
        return HttpResponse("<h1>{}{}<h1>".format(foods,languages))
    return render(request,'multiselect.html')

from django.core.files.storage import FileSystemStorage

#uploading and displaying the uploaded image
def img_upld(request):
    return render(request,"img_upld.html")

from myapp.utilities import store_image
def img_display(request):
    file_url=False
    if request.method=="POST" and request.FILES:
        image1=request.FILES.get('sam1')
        image2=request.FILES.get('sam2')
        file_urls=map(store_image,[image1,image2])        
                
    return render(request,"img_display.html",context={'file_urls':file_urls})

from myapp import forms

def builtinforms(request):
    if request.method=="POST":
        form=forms.SampleForm(request.POST,request.FILES)#im creating a form instance with the data filled the all the firlds will get th
        #the specified value
        if form.is_valid():
            #cleaned_data is varible in form instance that holds the dictonary containing the data that we 
            #have filled
            first_name=form.cleaned_data.get('first_name')
            last_name=form.cleaned_data.get('last_name')
            email=form.cleaned_data.get('email')
            phno=form.cleaned_data.get('phno')
            pwd=form.cleaned_data.get('pwd')
            birth_day=form.cleaned_data.get('birth_day')
            birth_month=form.cleaned_data.get('birth_month')
            birth_year=form.cleaned_data.get('birth_year')
            gender=form.cleaned_data.get('gender')
            image=form.cleaned_data.get('image')
            store_image(image)
            data=form.cleaned_data
            return render(request,"display_data.html",context=data)
    form=forms.SampleForm()
    return render(request,'builtin.html',{'form':form})

#forms is a file or a library 
#in forms Form is a class so we inherit from forms.Form

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
    <title>BASE Page</title>
    {% endblock %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-grid.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-grid.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-reboot.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-reboot.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

</head>
<body>
  {% include "partials/_topbar.html" %}
  {% include "partials/_navbar.html" %}
  
    {% block content %}
      <div class="container">
        <div class="jumbotron">
          <h1>Welcome to base page</h1>
          <img src="{% static 'images/django_logo.png' %}" alt="No Image Found" height="50" width="100">
        </div>
      </div>
    {% endblock %}


    {% include "partials/_footer.html" %}

</body>
</html>

templates/builtin.html
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>builtin forms</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</head>
<body>
    
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
            <div class="col-2">
                {{form.first_name|as_crispy_field}}
            </div>
            <div class="col-2">
                {{form.last_name|as_crispy_field}}
            </div>
        </div> 
        <div class="row"> 
            <div class="col-2">
                {{form.email|as_crispy_field}}
            </div>
            <div class="col-2">
                {{form.phno|as_crispy_field}}
            </div>
            <div class="col-2">
                {{form.pwd|as_crispy_field}}
            </div>
        </div>
        <div class="row">
            <div class="col-2">
                {{form.birth_day|as_crispy_field}}
            </div>
            <div class="col-2">
                {{form.birth_month|as_crispy_field}}
            </div>
            <div class="col-2">
                {{form.birth_year|as_crispy_field}}
            </div>
        </div>
        
        {{form.gender|as_crispy_field}}
        {{form.image|as_crispy_field}}
            
        <!-- <table border="2pt">
        {{form.as_table}}>
    </table> -->
    <!-- <ul>
        {{ form.as_ul }}
    </ul> -->
        <input type="submit" value="Submit">
</table>
</body>
</html>

templates/display_data.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Display</title>
</head>
<body>
    <h1>{{first_name}}</h1>
    <h1>{{last_name}}</h1>
    <h1>{{email}}</h1>
    <h1>{{phno}}</h1>
    <h1>{{pwd}}</h1>
    <h1>{{birth_day}}</h1>
    <h1>{{birth_month}}</h1>
    <h1>{{birth_year}}</h1>
    <h1>{{gender}}</h1>
</body>
</html>

templates/get_demo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>GET Demo</title>
</head>
<body>
    <form method="GET">
        <label for="name">Name:</label>
        <input type="text" name="name" id="name">
        <input type="submit" value="Submit">
    </form>
    <h1>{{name}}</h1>
</body>
</html>

templates/img_display.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>image Display</title>
</head>
<body>
    {% for file_url in file_urls %}
    {% if file_url %}
    <img src="{{ file_url }}" alt="No Image Found" height="100" width="200">
  {% endif %}
    {% endfor %}
    
</body>
</html>

templates/img_upld.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>image uplaod</title>
</head>
<body>
    <form action="{% url 'myapp:img_disp' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        Image1:<input type="file" name="sam1" id="sam1"><br>
        Image2:<input type="file" name="sam2" id="sam2">
        <input type="submit" value="Submit">
    </form>
    
</body>
</html>

templates/multiselect.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MultiSelect and Checkboxes</title>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
        <label for="langauges">Choose Your Language:</label>
        <select name="language" id="languages" multiple>
            <option value="Python">Python</option>
            <option value="Java">Java</option>
            <option value="C#">C#</option>
            <option value="C">C Langauge</option>
            <option value="C++">C++</option>
        </select><br>
        <h6>Choose Your Food</h6>
        <label for="idli">
            Idli
        </label>
        <input type="checkbox" name="food" id="idli" value="IDLI">
        <label for="vada">
            vada
        </label>
        <input type="checkbox" name="food" id="vada" value="VADA">
        <label for="dosa">
            Dosa
        </label>
        <input type="checkbox" name="food" id="Dosa" value="DOSA">
        <label for="upma">
            upma
        </label>
        <input type="checkbox" name="food" id="upma" value="UPMA">
        <input type="submit" value="Submit">
    </form>
</body>
</html>

templates/myapp/home.html
{% extends "base.html" %}

{% block title %}
    <title>Home Page</title>
{% endblock %}

{% block content %}
      <div class="container">
        <div class="jumbotron">
            <h1>Welcome to Home page</h1>
        </div>
      </div>
{% endblock %}

templates/myapp/profile.html
{% extends "base.html" %}

{% block title %}
    <title>Profile Page</title>
{% endblock %}

{% block content %}
      <div class="container">
        <div class="jumbotron">
            <h1>Welcome to {{name}} Profile page</h1>
        </div>
      </div>
{% endblock %}

templates/partials/_footer.html
<!-- footer -->
<div class="alert alert-primary" role="alert">
    <center>Footer</center> 
  </div>

templates/partials/_navbar.html
<!-- navbar -->
  <div class="container">
    <ul class="nav">
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'myapp:profile' %}">Profile</a>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:register' %}">Register</a>
        </li>      
    </ul>
</div>

templates/partials/_topbar.html
<!-- topbar -->
<div class="alert alert-secondary" role="alert">
    <center>Top Bar</center> 
 </div>

templates/post_demo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>POST Demo</title>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
        <label for="name">Name:</label>
        <input type="text" name="name" id="name">
        <input type="submit" value="Submit">
    </form>
   
</body>
</html>